Cancer-Types:
  - LAML
  - ACC
  - BLCA
  - LGG
  - BRCA
  - CESC
  - CHOL
  - COAD
  - ESCA
  - GBM
  - HNSC
  - KICH
  - KIRC
  - KIRP
  - LIHC
  - LUAD
  - LUSC
  - DLBC
  - MESO
  - OV
  - PAAD
  - PCPG
  - PRAD
  - READ
  - SARC
  - SKCM
  - STAD
  - TGCT
  - THYM
  - THCA
  - UCS
  - UCEC
  - UVM
